* [1;34m230f6b6[m - [1;32m(58 seconds ago)[m [37mAdd README and setup application[m [2;37m- speedy[m[1;33m (HEAD -> KWUpdate, origin/master, origin/HEAD, master)[m
* [1;34mc0b5fb2[m - [1;32m(69 minutes ago)[m [37mLast?[m [2;37m- MrPaulMarshall[m[1;33m[m
* [1;34m57fba0c[m - [1;32m(3 hours ago)[m [37mAdd and fix tests, fix bugs and database[m [2;37m- speedy[m[1;33m[m
* [1;34mcdc0202[m - [1;32m(5 hours ago)[m [37mNew patient database[m [2;37m- speedy[m[1;33m[m
* [1;34m6819310[m - [1;32m(6 hours ago)[m [37mstrategies.txt[m [2;37m- MrPaulMarshall[m[1;33m[m
* [1;34mc8155be[m - [1;32m(6 hours ago)[m [37mLambda strategies[m [2;37m- MrPaulMarshall[m[1;33m[m
* [1;34m48e52ec[m - [1;32m(8 hours ago)[m [37mGreat refactor[m [2;37m- speedy[m[1;33m[m
*   [1;34m656a8ba[m - [1;32m(2 days ago)[m [37mMerge pull request #16 from krzwid/PMUpdate[m [2;37m- Paweł Marszał[m[1;33m[m
[32m|[m[33m\[m  
[32m|[m * [1;34m1a0bc4f[m - [1;32m(2 days ago)[m [37mSmacznego[m [2;37m- MrPaulMarshall[m[1;33m[m
[32m|[m[32m/[m  
* [1;34m3788abf[m - [1;32m(2 days ago)[m [37mAdd new parameters[m [2;37m- speedy[m[1;33m[m
* [1;34m712a2a3[m - [1;32m(2 days ago)[m [37mLittle correction[m [2;37m- MrPaulMarshall[m[1;33m[m
*   [1;34m90376b7[m - [1;32m(2 days ago)[m [37mMerge branch 'master' of https://github.com/krzwid/COVID-19-Simulator[m [2;37m- MrPaulMarshall[m[1;33m[m
[34m|[m[35m\[m  
[34m|[m *   [1;34m0398d3f[m - [1;32m(2 days ago)[m [37mMerge pull request #15 from krzwid/PMUpdate[m [2;37m- Paweł Marszał[m[1;33m[m
[34m|[m [36m|[m[1;31m\[m  
* [36m|[m [1;31m|[m [1;34m174e188[m - [1;32m(2 days ago)[m [37mShould work[m [2;37m- MrPaulMarshall[m[1;33m[m
[1;31m|[m [36m|[m[1;31m/[m  
[1;31m|[m[1;31m/[m[36m|[m   
* [36m|[m [1;34m7415e61[m - [1;32m(2 days ago)[m [37mEngine should work[m [2;37m- MrPaulMarshall[m[1;33m[m
[36m|[m[36m/[m  
* [1;34m4a06f00[m - [1;32m(2 days ago)[m [37mAdd drawing beautiful plots[m [2;37m- speedy[m[1;33m[m
*   [1;34ma01329d[m - [1;32m(2 days ago)[m [37mMerge pull request #14 from krzwid/PMUpdate[m [2;37m- Paweł Marszał[m[1;33m[m
[1;32m|[m[1;33m\[m  
[1;32m|[m * [1;34m9786ac8[m - [1;32m(2 days ago)[m [37mProsze bardzo[m [2;37m- MrPaulMarshall[m[1;33m[m
* [1;33m|[m   [1;34m8efab18[m - [1;32m(2 days ago)[m [37mMerge pull request #13 from krzwid/PMUpdate[m [2;37m- Paweł Marszał[m[1;33m[m
[1;34m|[m[1;33m\[m [1;33m\[m  
[1;34m|[m [1;33m|[m[1;33m/[m  
[1;34m|[m * [1;34ma5a065e[m - [1;32m(2 days ago)[m [37mBetter DailyData[m [2;37m- MrPaulMarshall[m[1;33m[m
[1;34m|[m[1;34m/[m  
* [1;34m94f4328[m - [1;32m(3 days ago)[m [37mTest of drawing plots[m [2;37m- speedy[m[1;33m[m
*   [1;34mc3fa08b[m - [1;32m(4 days ago)[m [37mMerge pull request #12 from krzwid/PMUpdate[m [2;37m- Paweł Marszał[m[1;33m[m
[1;36m|[m[31m\[m  
[1;36m|[m * [1;34md643395[m - [1;32m(4 days ago)[m [37mFixed heap - in/out room[m [2;37m- MrPaulMarshall[m[1;33m[m
[1;36m|[m[1;36m/[m  
* [1;34m60d7b75[m - [1;32m(5 days ago)[m [37mWorks but EVERYBODY DIES![m [2;37m- speedy[m[1;33m[m
* [1;34meda2e58[m - [1;32m(5 days ago)[m [37mImplement methods to simluate[m [2;37m- speedy[m[1;33m[m
*   [1;34me19e8ac[m - [1;32m(5 days ago)[m [37mMerge branch 'master' into KWUpdate[m [2;37m- speedy[m[1;33m[m
[32m|[m[33m\[m  
[32m|[m *   [1;34m74cbcb9[m - [1;32m(5 days ago)[m [37mMerge pull request #11 from krzwid/PMUpdate[m [2;37m- Paweł Marszał[m[1;33m[m
[32m|[m [34m|[m[35m\[m  
[32m|[m [34m|[m * [1;34ma8d4f16[m - [1;32m(5 days ago)[m [37mWielki Skok[m [2;37m- MrPaulMarshall[m[1;33m[m
* [34m|[m [35m|[m [1;34mf6e620b[m - [1;32m(5 days ago)[m [37mModify canGoIn method[m [2;37m- speedy[m[1;33m[m
[34m|[m[34m/[m [35m/[m  
* [35m|[m   [1;34m54a9af5[m - [1;32m(5 days ago)[m [37mMerge pull request #10 from krzwid/PMUpdate[m [2;37m- Paweł Marszał[m[1;33m[m
[36m|[m[35m\[m [35m\[m  
[36m|[m [35m|[m[35m/[m  
[36m|[m * [1;34mef44bd8[m - [1;32m(5 days ago)[m [37mExceptions[m [2;37m- MrPaulMarshall[m[1;33m[m
* [1;31m|[m   [1;34m9934bbc[m - [1;32m(5 days ago)[m [37mMerge pull request #9 from krzwid/PMUpdate[m [2;37m- Paweł Marszał[m[1;33m[m
[1;32m|[m[1;31m\[m [1;31m\[m  
[1;32m|[m [1;31m|[m[1;31m/[m  
[1;32m|[m * [1;34me3def61[m - [1;32m(5 days ago)[m [37mSim - line42[m [2;37m- MrPaulMarshall[m[1;33m[m
* [1;33m|[m   [1;34m990346d[m - [1;32m(5 days ago)[m [37mMerge pull request #8 from krzwid/PMUpdate[m [2;37m- Paweł Marszał[m[1;33m[m
[1;34m|[m[1;33m\[m [1;33m\[m  
[1;34m|[m [1;33m|[m[1;33m/[m  
[1;34m|[m *   [1;34m7081b16[m - [1;32m(5 days ago)[m [37mMerge branch 'master' into PMUpdate[m [2;37m- Paweł Marszał[m[1;33m[m
[1;34m|[m [1;36m|[m[1;34m\[m  
[1;34m|[m [1;36m|[m[1;34m/[m  
[1;34m|[m[1;34m/[m[1;36m|[m   
* [1;36m|[m [1;34m4c06af6[m - [1;32m(5 days ago)[m [37mStart main engine function[m [2;37m- speedy[m[1;33m[m
[31m|[m * [1;34mbb46289[m - [1;32m(5 days ago)[m [37mPartial update[m [2;37m- MrPaulMarshall[m[1;33m[m
[31m|[m[31m/[m  
* [1;34m99c681e[m - [1;32m(6 days ago)[m [37mHospital-building[m [2;37m- MrPaulMarshall[m[1;33m[m
* [1;34m9e978ec[m - [1;32m(6 days ago)[m [37mEngine[m [2;37m- MrPaulMarshall[m[1;33m[m
*   [1;34m8407e9a[m - [1;32m(6 days ago)[m [37mMerge pull request #7 from krzwid/PMUpdate[m [2;37m- Paweł Marszał[m[1;33m[m
[32m|[m[33m\[m  
[32m|[m * [1;34m738240d[m - [1;32m(6 days ago)[m [37mParams[m [2;37m- MrPaulMarshall[m[1;33m[m
* [33m|[m [1;34mc7f8be5[m - [1;32m(6 days ago)[m [37mAdd patient and staff files[m [2;37m- speedy[m[1;33m[m
[33m|[m[33m/[m  
* [1;34m2c2f9e8[m - [1;32m(10 days ago)[m [37mAdd BasicEngineTest[m [2;37m- speedy[m[1;33m[m
* [1;34mfadd09a[m - [1;32m(10 days ago)[m [37mAdd tests and fix some bugs[m [2;37m- speedy[m[1;33m[m
*   [1;34m8847e9a[m - [1;32m(10 days ago)[m [37mmerge KWUpdate Merge branch 'master' into KWUpdate[m [2;37m- speedy[m[1;33m[m
[34m|[m[35m\[m  
[34m|[m *   [1;34m20c4589[m - [1;32m(13 days ago)[m [37mMerge pull request #6 from krzwid/PMUpdate[m [2;37m- Paweł Marszał[m[1;33m[m
[34m|[m [36m|[m[1;31m\[m  
[34m|[m [36m|[m * [1;34m1372280[m - [1;32m(13 days ago)[m [37mAdvanced Config[m [2;37m- MrPaulMarshall[m[1;33m[m
[34m|[m [36m|[m[36m/[m  
[34m|[m *   [1;34m1920241[m - [1;32m(13 days ago)[m [37mMerge pull request #5 from krzwid/PMUpdate[m [2;37m- Paweł Marszał[m[1;33m[m
[34m|[m [1;32m|[m[1;33m\[m  
[34m|[m [1;32m|[m * [1;34m5cf7682[m - [1;32m(13 days ago)[m [37mEngine[m [2;37m- MrPaulMarshall[m[1;33m[m
[34m|[m [1;32m|[m[1;32m/[m  
* [1;32m|[m [1;34md4476be[m - [1;32m(10 days ago)[m [37mupdate files[m [2;37m- speedy[m[1;33m[m
[1;32m|[m[1;32m/[m  
* [1;34m71e0c6e[m - [1;32m(13 days ago)[m [37mChange Room interface and implement it in PatientRoom and StaffRoom[m [2;37m- speedy[m[1;33m[m
*   [1;34md15f1b3[m - [1;32m(13 days ago)[m [37mMerge pull request #4 from krzwid/PMUpdate[m [2;37m- Paweł Marszał[m[1;33m[m
[1;34m|[m[1;35m\[m  
[1;34m|[m * [1;34m5df1eda[m - [1;32m(13 days ago)[m [37mEngine[m [2;37m- MrPaulMarshall[m[1;33m[m
[1;34m|[m[1;34m/[m  
* [1;34mf9dc18c[m - [1;32m(13 days ago)[m [37mUpdate DailyData[m [2;37m- speedy[m[1;33m[m
*   [1;34m05d1e2d[m - [1;32m(13 days ago)[m [37mMerge branch 'master' into KWUpdate[m [2;37m- speedy[m[1;33m[m
[1;36m|[m[31m\[m  
[1;36m|[m *   [1;34mfadab5e[m - [1;32m(13 days ago)[m [37mMerge pull request #3 from krzwid/PMUpdate[m [2;37m- Paweł Marszał[m[1;33m[m
[1;36m|[m [32m|[m[33m\[m  
[1;36m|[m [32m|[m * [1;34m6033459[m - [1;32m(13 days ago)[m [37mConfig[m [2;37m- MrPaulMarshall[m[1;33m[m
[1;36m|[m [32m|[m[32m/[m  
* [32m|[m [1;34m8859860[m - [1;32m(13 days ago)[m [37mAdd new files[m [2;37m- speedy[m[1;33m[m
[32m|[m[32m/[m  
* [1;34m58faa29[m - [1;32m(13 days ago)[m [37mAdd reading from file[m [2;37m- speedy[m[1;33m[m
* [1;34m27b1a15[m - [1;32m(13 days ago)[m [37mFix patient and staff room[m [2;37m- speedy[m[1;33m[m
*   [1;34m2e03816[m - [1;32m(3 weeks ago)[m [37mMerge branch 'PMUpdate'[m [2;37m- MrPaulMarshall[m[1;33m[m
[34m|[m[35m\[m  
[34m|[m * [1;34m4b58bb5[m - [1;32m(3 weeks ago)[m [37mtest commit[m [2;37m- MrPaulMarshall[m[1;33m[m
* [35m|[m   [1;34mcccd751[m - [1;32m(3 weeks ago)[m [37mMerge master[m [2;37m- speedy[m[1;33m (origin/KWUpdate)[m
[36m|[m[1;31m\[m [35m\[m  
[36m|[m * [35m\[m   [1;34m9a150f6[m - [1;32m(3 weeks ago)[m [37mMerge pull request #2 from krzwid/PMUpdate[m [2;37m- Paweł Marszał[m[1;33m[m
[36m|[m [1;32m|[m[35m\[m [35m\[m  
[36m|[m [1;32m|[m [35m|[m[35m/[m  
[36m|[m [1;32m|[m * [1;34m84b6708[m - [1;32m(3 weeks ago)[m [37min-progress[m [2;37m- MrPaulMarshall[m[1;33m[m
[36m|[m [1;32m|[m *   [1;34ma45d963[m - [1;32m(3 weeks ago)[m [37mMerge branch 'master' of https://github.com/krzwid/COVID-19-Simulator[m [2;37m- MrPaulMarshall[m[1;33m[m
[36m|[m [1;32m|[m [1;34m|[m[1;32m\[m  
[36m|[m [1;32m|[m [1;34m|[m[1;32m/[m  
[36m|[m [1;32m|[m[1;32m/[m[1;34m|[m   
[36m|[m [1;32m|[m *   [1;34ma2f5dd8[m - [1;32m(3 weeks ago)[m [37mMerge branch 'master' of https://github.com/krzwid/COVID-19-Simulator[m [2;37m- MrPaulMarshall[m[1;33m[m
[36m|[m [1;32m|[m [1;36m|[m[31m\[m  
[36m|[m [1;32m|[m * [31m\[m   [1;34m579aa31[m - [1;32m(3 weeks ago)[m [37mMerge branch 'master' of https://github.com/krzwid/COVID-19-Simulator[m [2;37m- MrPaulMarshall[m[1;33m[m
[36m|[m [1;32m|[m [32m|[m[33m\[m [31m\[m  
[36m|[m [1;32m|[m * [33m|[m [31m|[m [1;34m80a51c0[m - [1;32m(3 weeks ago)[m [37mUpdate DailyData.scala[m [2;37m- MrPaulMarshall[m[1;33m[m
* [1;32m|[m [33m|[m [33m|[m [31m|[m [1;34m50d2e00[m - [1;32m(3 weeks ago)[m [37mImplement methods to MapSites[m [2;37m- speedy[m[1;33m[m
[1;32m|[m[1;32m/[m [33m/[m [33m/[m [31m/[m  
* [33m|[m [33m|[m [31m|[m   [1;34m6c833d9[m - [1;32m(3 weeks ago)[m [37mMerge pull request #1 from krzwid/PMUpdate[m [2;37m- Paweł Marszał[m[1;33m[m
[31m|[m[35m\[m [33m\[m [33m\[m [31m\[m  
[31m|[m [35m|[m[31m_[m[33m|[m[31m_[m[33m|[m[31m/[m  
[31m|[m[31m/[m[35m|[m [33m|[m [33m|[m   
[31m|[m * [33m|[m [33m|[m [1;34mab143fc[m - [1;32m(3 weeks ago)[m [37mmmm[m [2;37m- MrPaulMarshall[m[1;33m[m
* [35m|[m [33m|[m [33m|[m [1;34mf12fe33[m - [1;32m(3 weeks ago)[m [37mAdd floor and modify hospital[m [2;37m- speedy[m[1;33m[m
[33m|[m [35m|[m[33m_[m[33m|[m[33m/[m  
[33m|[m[33m/[m[35m|[m [33m|[m   
* [35m|[m [33m|[m   [1;34mcece378[m - [1;32m(3 weeks ago)[m [37mTest commit[m [2;37m- speedy[m[1;33m[m
[36m|[m[33m\[m [35m\[m [33m\[m  
[36m|[m [33m|[m [35m|[m[33m/[m  
[36m|[m [33m|[m[33m/[m[35m|[m   
[36m|[m * [35m|[m [1;34m9ce0771[m - [1;32m(3 weeks ago)[m [37mTest commit[m [2;37m- MrPaulMarshall[m[1;33m[m
[36m|[m [35m|[m[35m/[m  
* [35m|[m [1;34me381c64[m - [1;32m(3 weeks ago)[m [37mUpdate to other branch[m [2;37m- MrPaulMarshall[m[1;33m[m
[35m|[m[35m/[m  
* [1;34mfc14d36[m - [1;32m(3 weeks ago)[m [37mInitial commit[m [2;37m- MrPaulMarshall[m[1;33m (origin/PMUpdate)[m